// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Grid$ReactTemplate = require("./Grid.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Grid$ReactTemplate.make(/* array */[
              "blue",
              "blue",
              "red",
              "green"
            ], /* array */[])), "hello-color");

/*  Not a pure module */
