// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var HelloColor$ReactTemplate = require("./HelloColor.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, HelloColor$ReactTemplate.make("pink", "foo", /* array */[])), "hello-color");

/*  Not a pure module */
